### PR TITLE
Update to font awesome 5

### LINKED ISSUE #6: How to set size relative to container?
As I understood it, for now sizes are absolute in pixels. Is there a way to specify a relative size instead?

### LINKED ISSUE #9: Font awesome 5 support
Hey!

I was thinkering this afternoon about creating an elm package containing every [font awesome 5 icons](https://fontawesome.com/?utm_source=font_awesome_homepage&utm_medium=display&utm_campaign=fa5_released&utm_content=banner) before I found your project.

The new release already contains all icons in svg format in `advanced-options/raw-svg/`. 

Will you be interested into switching to the new version of font awesome ? Of course, I can contribute it myself but I prefer to check with you if that's ok.

### PR DESCRIPTION
**Pull request by charlesvdv**
This PR comes with various improvments: 

- Improve `gen_code.sh`
  - Use svg provided directly by fontawesome
  - Use xpath instead of sed for better resiliance
- Split icons by different types, namely *brands*, *solid* and *regular*
- Icons inherit directly from the parent style (color and size)
- Go from 694 to 903 icons (thanks to the new fontawesome version)

Close #9 and indirectly close #6 (since the size is now inherited, it's easy to use `em` to have a relative size). 

I already bumped the package version, but if you don't want to I have no problem to revert that commit.

### CODE REVIEW

**Comment by alicebob** [comment]
Any update about this? @jystic ?

**Comment by jystic** [comment]
Sorry, been a bit busy, moving countries :) I probably won't get to this for a week or so, this looks good though!

**Comment by pdilyard** [comment]
Bumping, I'd love to see this merged!

**Comment by jystic** [comment]
Thanks for the bump, this all looks good :100: will do a release!

**Comment by jystic** [comment]
http://package.elm-lang.org/packages/jystic/elm-font-awesome/3.0.0

**Comment by alicebob** [comment]
Nice! Thanks @charlesvdv and @jystic !

**Pull request merged**
